name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
#          pip install pytest      Can be added if wanted

      # - name: Run tests          Can be added if wanted
      #   run: |
      #     pytest

  Docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read version from file
        id: read_version
        run: |
          VERSION=$(cat version)
          BRANCH=$(echo $GITHUB_REF | awk -F/ '{print $3}')

          if [[ "$BRANCH" == "develop" ]]; then
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            VERSION="${VERSION}-SNAPSHOT-${TIMESTAMP}"
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t josenavpoc/my-python-web-app:latest .
          docker build -t josenavpoc/my-python-web-app:${{ env.VERSION }} .

      - name: Push Docker image
        run: |
          docker push josenavpoc/my-python-web-app:latest .
          docker push josenavpoc/my-python-web-app:${{ env.VERSION }}
